FROM php:7.4.1-fpm

SHELL ["/bin/bash", "-c"]

COPY ./php-config /usr/local/etc/php

RUN apt-get update; \
    apt-get install -y --no-install-recommends \
    git zip unzip libzip-dev libfreetype6-dev \
    libjpeg62-turbo-dev libpng-dev

RUN docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/
RUN docker-php-ext-install \
    bcmath pdo_mysql \
    gd zip

COPY --from=composer:1.9.1 /usr/bin/composer /usr/bin/composer
RUN composer --version

ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 12.14.1
RUN mkdir -p $NVM_DIR

RUN curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
RUN source $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

RUN npm -v
RUN node -v

WORKDIR /app
# COPY . . # Copy source code to /app

CMD ["/bin/bash"]
